config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: %i(show)
  resources :people, only: %i(index) do
    collection do
      post :import
    end
  end
  root 'dashboard#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show; end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def import
    if people = ImportCSV.call(person_params[:import_file])
      redirect_to people_path, notice: "#{people.try(:count) || 0} People Imported Sucessfully"
    else
      redirect_to root_path, notice: 'Something Went Wrong!'
    end
  end

  private

  def person_params
    params.require(:person).permit(:import_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dashboard/show.html.erb
<h1>Mov</h1>
<%= link_to 'All People', people_path %>
<p>Upload <code>.csv</code> file to import</p>
<%= simple_form_for :person, url: import_people_path, method: :post do |f| %>
  <%= f.input :import_file, as: :file %>
  <%= f.button :submit, 'Import' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mov</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <article class="flashes">
      <% if flash.any? %>
        <% flash.each do |status, text| %>
          <div class="flash-<%= status %>">
            <span><%= text %></span>
          </div>
        <% end %>
      <% end %>
    </article>
    <%= yield %>
  </body>
</html>

app/views/people/_collection.html.erb
<% unless people.blank? %>
  <table>
    <thead>
    <tr>
      <th><%= Person.human_attribute_name :name %></th>
      <th><%= Person.human_attribute_name :email %></th>
      <th><%= Person.human_attribute_name :telephone_number %></th>
      <th><%= Person.human_attribute_name :website %></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.telephone_number %></td>
        <td><%= person.website %></td>
        <td><%= l person.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No record found</p>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>
<%= render 'collection', people: @people %>

<%= link_to 'Back to Dashboard', root_path %>